name: "First Work Flow"

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run:
          echo "Hello GitHub Actions. Hi"
      
      - name: Print Bye
        run: 
          echo  "Hello GitHub Action. GoodBye"
